### ISSUE TITLE
How to use the new config/targets.js system? 

### ISSUE THREAD

**Issue by ghost** [ember-cli/ember-cli.github.io#139]
With the ember-cli@2.13.0 I have a new config/targets.js file. How can I use it?

I read the RFC but there isn't a WIKI more clear?

The syntax for the browsers?

**Comment by stefanpenner** [comment]
cc @cibernox / @rwjblue

**Comment by robbiespeed** [comment]
I actually ran into an issue because of there not being much documentation around this. I figured since my application only needed to support the latest versions of Chrome that I could just target that. Turns out doing so breaks minification. 

The issue was annoying to track down, and the only place I found this being talked about is @rwjblue's [blog](http://rwjblue.com/2017/04/21/ember-cli-targets/#minification)

**Comment by cibernox** [comment]
I also think that @rwjblue blog is a a good explanation, but perhaps an entry in the guides would be nice.
