### ISSUE TITLE
Built-in generator list difficult to find in the docs

### ISSUE THREAD

**Issue by derekwsgray** [ember-cli/ember-cli.github.io#181]
The navigation to: https://ember-cli.com/extending/#detailed-list-of-blueprints-and-their-use
is very difficult to find for someone who wants a quick reference to the list of generators with ember-cli.
Currently it sits under EXTENDING and buried in details about, well, extending, which isn't what someone wanting to see what generators there are is doing.

(I realize I can execute "ember generate --help' to get the list in a console, but still, its long and more easily browsed in a page as a reference.)

**Comment by locks** [comment]
@derekwsgray Thanks for reaching out, but `ember generate --help` is the best way to get that information because we will also list any blueprints provided by add-ons you might have installed, like `ember-data`. Even the default experience might vary depending on the version, making the page even less useful and possibly misleading.
We're working on editor integration, which might help with surfacing this information.
